apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    app: frontend

spec:
  replicas: {{ .Values.frontend.replicas | default 2 }}
  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend
    spec: 
      containers:
      - name: frontend
        image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
        imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.frontend.port }}
            protocol: TCP

        resources:
          requests:
            cpu: {{ .Values.frontend.cpuRequest }}
            memory: {{ .Values.frontend.memoryRequest }}  
          limits:
            cpu: {{ .Values.frontend.cpuLimit }}
            memory: {{ .Values.frontend.memoryLimit }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.port }}
          initialDelaySeconds: 15
          periodSeconds: 20


---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: frontend

spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
  selector:
    app: frontend



  
