apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: website-db-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: website-SC
  resources:
    requests:
      storage: 10Gi