apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  POSTGRES_DB: cHJvZm91bmRfZGI=
  POSTGRES_USER: cHJvZm91bmRfdXNlcg==
  POSTGRES_PASSWORD: cmFwX3NlY3JldA==
  